language: node_js
node_js:
  - "11"

os:
  - linux
  - osx

deploy:
  edge: true

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

addons:
  apt:
    packages:
      - graphviz
      - libgconf-2-4

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ln -s package.linux.json package.json; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ln -s package.mac.json package.json; fi
  - yarn --pure-lockfile

script:
  - yarn test
  - if [ "$TRAVIS_TAG" ]; then yarn build; fi

deploy:
  - provider: releases
    api-key: $GH_TOKEN
    file_glob: true
    file:
      - dist/*.dmg
      - dist/*.AppImage
    skip_cleanup: true
    on:
      tags: true
  - provider: snap
    snap: dist/*.snap
    channel: stable
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
